server:
  port: 8080

logging:
  group:
    sender: ru.kotikov.soapspringboot
  level:
    sender: DEBUG
    org.springframework.jdbc.core: TRACE

spring:
  datasource:
    url: jdbc:h2:mem:dbname
    driverClassName: org.h2.Driver
    username:
    password:

management:
  server:
    port: 8081

sender:
  confirmationFixedThreads: 5
  messageProcessingFixedThreads: 5
  outputUrl: http://localhost:8080/api/v1
  senderName: Kotikov

