server:
  port: ${PORT}

management:
  server:
    port: ${MANAGEMENT_PORT}

logging:
  group:
    sender: ${LOG_GROUP_SENDER}
  level:
    sender: ${LOG_SENDER_LEVEL}
  file:
    file-name: ${LOG_FILE_NAME}
    total-size: ${LOG_TOTAL_SIZE_CAP}
  logback:
    rollingpolicy:
      max-file-size: ${LOG_MAX_FILE_SIZE}
      max-history: ${LOG_MAX_HISTORY}

spring:
  datasource:
    url: ${INCIDENT_DATASOURCE_URL}
    username: ${INCIDENT_DATASOURCE_USERNAME}
    password: ${INCIDENT_DATASOURCE_PASSWORD}

sender:
  senderName: ${SENDER_NAME}